#!/usr/bin/env perl

use strict;
use warnings;
use OptArgs2 'class_optargs';

# Include the project module directory.
use FindBin;
use File::Spec;
use lib File::Spec->catdir($FindBin::Bin, '..', 'lib');

use App::pickle::OptArgs;
 
my ($class, $opts) = class_optargs('App::pickle');
eval "require $class" or die $@;
$class->new($opts)->run;

__END__

=back

=head1 AUTHOR

Nathan Campos <nathan@innoveworkshop.com>

=head1 COPYRIGHT

Copyright (c) 2022- Nathan Campos.

=cut
